### ISSUE TITLE
add support for hexadecimal defined integers

### ISSUE THREAD

**Issue by JakubLukas** [OndrejRitomsky/toolbox#2]
that would be great :)

**Comment by OndrejRitomsky** [comment]
There is more separate projects in this repo, please add prefix for project.
As for json, hexa numbers arent in the spec. as far as I understand, only ints, fractions and exponent formats. (In strings there is hexa escape sequence used for utf characters - not supported)
But might look into it.

**Comment by OndrejRitomsky** [comment]
Done
